import type { MemorialContext } from './types';

export const MEMORIAL_ID = 'mami-christiana-enanga-besong';
export const MEMORIAL_SLUG = 'mami-christiana-enanga-besong';

const portrait = '/images/portrait.jpg';
const programme = '/images/funeral-programme.jpg';

export const demoContext: MemorialContext = {
  memorial: {
    id: MEMORIAL_ID,
    slug: MEMORIAL_SLUG,
    fullName: 'Mami Christiana Enanga Besong',
    maidenName: 'Njie Nambeke',
    portraitUrl: portrait,
    bornOn: '1936-05-24',
    diedOn: '2026-08-14',
    tagline: 'Her legacy lives on in us all.',
    shortTribute:
      'A beloved mother, a cherished grandmother, a pillar of family, a legacy forever. Her kindness lives on. Her love endures. Her legacy inspires us all.',
    obituaryHtml: `<p>Mami Christiana Enanga Besong, née Njie Nambeke, was called home on 14 August 2026 at the age of 90. Born on 24 May 1936, she was celebrated by her family as a beloved mother, a cherished grandmother, and a pillar of the family whose kindness, love, and legacy continue to inspire all who knew her.</p>
<p>The family will honour 90 years of grace, love, and legacy through a Funeral and Thanksgiving Programme from 7 to 19 November 2026. Gatherings will be held at the family residence in Clerk’s Quarter, Ebenezer Baptist Church Limbe, and the family compound in Limbola.</p>
<p>Family and friends are invited to celebrate a life well lived. “Blessed are the dead who die in the Lord.” — Revelation 14:13</p>`,
    isPublished: true,
    programPdfUrl: programme,
  },
  biographySections: [
    {
      id: 'bio-1',
      memorialId: MEMORIAL_ID,
      kind: 'childhood',
      heading: 'Family & Legacy',
      body: 'Mami Christiana Enanga Besong, née Njie Nambeke, was a beloved mother, a cherished grandmother, and a pillar of her family. Born on 24 May 1936, she lived 90 years of grace, love, and legacy. Her family across Cameroon, Germany, the United States, and Canada continues to honour the life she lived.',
      sortOrder: 1,
    },
    {
      id: 'bio-2',
      memorialId: MEMORIAL_ID,
      kind: 'faith',
      heading: 'Faith',
      body: 'The family will give thanks for her life at Ebenezer Baptist Church Limbe, where the funeral service and special thanksgiving church service will be held. Scripture chosen in her honour: “Blessed are the dead who die in the Lord.” — Revelation 14:13.',
      sortOrder: 2,
    },
    {
      id: 'bio-3',
      memorialId: MEMORIAL_ID,
      kind: 'qualities',
      heading: 'A Life Well Lived',
      body: 'Her kindness lives on. Her love endures. Her legacy inspires us all. She is remembered as a pillar of family — a legacy forever, forever in our hearts.',
      sortOrder: 3,
    },
    {
      id: 'bio-4',
      memorialId: MEMORIAL_ID,
      kind: 'quotes',
      heading: 'In Honour of Mami',
      body: '“Her legacy lives on in us all.” The family celebrates 90 years of grace, love, and legacy, and invites all who loved her to gather in Clerk’s Quarter, Limbe, and Limbola.',
      sortOrder: 4,
    },
  ],
  timelineEvents: [
    {
      id: 'tl-1',
      memorialId: MEMORIAL_ID,
      eventDate: '1936-05-24',
      title: 'Sunrise',
      description: 'Mami Christiana Enanga Besong, née Njie Nambeke, was born.',
      sortOrder: 1,
    },
    {
      id: 'tl-2',
      memorialId: MEMORIAL_ID,
      eventDate: '2026-08-14',
      title: 'Sunset',
      description: 'Called home after 90 years of grace, love, and legacy.',
      sortOrder: 2,
    },
    {
      id: 'tl-3',
      memorialId: MEMORIAL_ID,
      eventDate: '2026-11-07',
      title: 'Opening of Mourning',
      description: 'Funeral and Thanksgiving Programme begins at the family residence, Clerk’s Quarter.',
      sortOrder: 3,
    },
    {
      id: 'tl-4',
      memorialId: MEMORIAL_ID,
      eventDate: '2026-11-14',
      title: 'Funeral, Burial & Grand Celebration of Life',
      description: 'Removal, viewing, funeral service at Ebenezer Baptist Church Limbe, burial at the family compound Limbola, and a grand celebration of Mami’s 90-year legacy.',
      sortOrder: 4,
    },
    {
      id: 'tl-5',
      memorialId: MEMORIAL_ID,
      eventDate: '2026-11-15',
      title: 'Special Thanksgiving Church Service',
      description: 'Thanksgiving service at Ebenezer Baptist Church Limbe, followed by a reception at the family residence.',
      sortOrder: 5,
    },
    {
      id: 'tl-6',
      memorialId: MEMORIAL_ID,
      eventDate: '2026-11-19',
      title: 'Sasa / Cultural Feast',
      description: 'Cultural feast at the family compound, Limbola.',
      sortOrder: 6,
    },
  ],
  familyMembers: [
    { id: 'fam-1', memorialId: MEMORIAL_ID, fullName: 'Chief Moses Obenofunde', relation: 'Cameroon', sortOrder: 1 },
    { id: 'fam-2', memorialId: MEMORIAL_ID, fullName: 'Oben Francis Essie', relation: 'Cameroon', sortOrder: 2 },
    { id: 'fam-3', memorialId: MEMORIAL_ID, fullName: 'Silo Oben Bertha', relation: 'Cameroon', sortOrder: 3 },
    { id: 'fam-4', memorialId: MEMORIAL_ID, fullName: 'Hillary Akem Oben', relation: 'Cameroon', sortOrder: 4 },
    { id: 'fam-5', memorialId: MEMORIAL_ID, fullName: 'Benjamin Tanyi Oben', relation: 'Cameroon', sortOrder: 5 },
    { id: 'fam-6', memorialId: MEMORIAL_ID, fullName: 'Samuel Njie Besong', relation: 'Germany', sortOrder: 6 },
    { id: 'fam-7', memorialId: MEMORIAL_ID, fullName: 'Obaley Oben Besong', relation: 'Germany', sortOrder: 7 },
    { id: 'fam-8', memorialId: MEMORIAL_ID, fullName: 'Robert Molango Oben', relation: 'Germany', sortOrder: 8 },
    { id: 'fam-9', memorialId: MEMORIAL_ID, fullName: 'Apst Dr. Drusilla Dinka', relation: 'USA', sortOrder: 9 },
    { id: 'fam-10', memorialId: MEMORIAL_ID, fullName: 'Sessekou Awu Moses Besong', relation: 'USA', sortOrder: 10 },
    { id: 'fam-11', memorialId: MEMORIAL_ID, fullName: 'Mrs Helen Enanga Nche', relation: 'USA', sortOrder: 11 },
    { id: 'fam-12', memorialId: MEMORIAL_ID, fullName: 'Edward Besong Oben', relation: 'Canada', sortOrder: 12 },
  ],
  funeralEvents: [
    {
      id: 'fe-1',
      memorialId: MEMORIAL_ID,
      kind: 'visitation',
      title: 'Opening of Mourning',
      startsAt: '2026-11-07T16:00:00+01:00',
      timeLabel: '04:00 PM',
      venueName: 'Family Residence, Clerk’s Quarter',
      address: 'Clerk’s Quarter, Limbe, Cameroon',
    },
    {
      id: 'fe-2',
      memorialId: MEMORIAL_ID,
      kind: 'visitation',
      title: 'Celebrating Her Life Story',
      startsAt: '2026-11-08T13:30:00+01:00',
      timeLabel: '01:30 PM',
      venueName: 'Family Residence, Clerk’s Quarter',
      address: 'Clerk’s Quarter, Limbe, Cameroon',
    },
    {
      id: 'fe-3',
      memorialId: MEMORIAL_ID,
      kind: 'visitation',
      title: 'Community, Friends & Relationships Day',
      startsAt: '2026-11-09T16:00:00+01:00',
      timeLabel: '04:00 PM',
      venueName: 'Family Residence, Clerk’s Quarter',
      address: 'Clerk’s Quarter, Limbe, Cameroon',
    },
    {
      id: 'fe-4',
      memorialId: MEMORIAL_ID,
      kind: 'visitation',
      title: 'Children, Grandchildren & Generations Day',
      startsAt: '2026-11-10T16:00:00+01:00',
      timeLabel: '04:00 PM',
      venueName: 'Family Residence, Clerk’s Quarter',
      address: 'Clerk’s Quarter, Limbe, Cameroon',
    },
    {
      id: 'fe-5',
      memorialId: MEMORIAL_ID,
      kind: 'reception',
      title: 'Cultural Day',
      startsAt: '2026-11-11T16:00:00+01:00',
      timeLabel: '04:00 PM – 12:00 PM',
      venueName: 'Family Residence, Clerk’s Quarter',
      address: 'Clerk’s Quarter, Limbe, Cameroon',
    },
    {
      id: 'fe-6',
      memorialId: MEMORIAL_ID,
      kind: 'visitation',
      title: 'Faith & Spiritual Legacy Day',
      startsAt: '2026-11-12T15:00:00+01:00',
      endsAt: '2026-11-12T22:00:00+01:00',
      timeLabel: '03:00 PM – 10:00 PM',
      venueName: 'Family Residence, Clerk’s Quarter',
      address: 'Clerk’s Quarter, Limbe, Cameroon',
    },
    {
      id: 'fe-7',
      memorialId: MEMORIAL_ID,
      kind: 'visitation',
      title: 'Wake-Keeping Without the Corpse',
      startsAt: '2026-11-13T18:00:00+01:00',
      timeLabel: '06:00 PM – Till Dawn',
      venueName: 'Family Residence, Clerk’s Quarter',
      address: 'Clerk’s Quarter, Limbe, Cameroon',
    },
    {
      id: 'fe-8',
      memorialId: MEMORIAL_ID,
      kind: 'visitation',
      title: 'I. Removal',
      startsAt: '2026-11-14T06:00:00+01:00',
      timeLabel: '06:00 AM',
      venueName: 'Limbe Regional Hospital Mortuary',
      address: 'Limbe, Cameroon',
      notes: 'Removal, funeral, burial, and grand celebration of life.',
    },
    {
      id: 'fe-9',
      memorialId: MEMORIAL_ID,
      kind: 'visitation',
      title: 'II. Viewing / Family Photographs',
      startsAt: '2026-11-14T07:00:00+01:00',
      endsAt: '2026-11-14T11:30:00+01:00',
      timeLabel: '07:00 AM – 11:30 AM',
      venueName: 'Family Residence, Clerk’s Quarter',
      address: 'Clerk’s Quarter, Limbe, Cameroon',
    },
    {
      id: 'fe-10',
      memorialId: MEMORIAL_ID,
      kind: 'service',
      title: 'Funeral Service',
      startsAt: '2026-11-14T12:00:00+01:00',
      endsAt: '2026-11-14T14:00:00+01:00',
      timeLabel: '12:00 PM – 02:00 PM',
      venueName: 'Ebenezer Baptist Church Limbe',
      address: 'Limbe, Cameroon',
    },
    {
      id: 'fe-11',
      memorialId: MEMORIAL_ID,
      kind: 'burial',
      title: 'IV. Burial & Final Farewell',
      startsAt: '2026-11-14T15:00:00+01:00',
      endsAt: '2026-11-14T16:00:00+01:00',
      timeLabel: '03:00 PM – 04:00 PM',
      venueName: 'Family Compound Limbola',
      address: 'Limbola, Cameroon',
    },
    {
      id: 'fe-12',
      memorialId: MEMORIAL_ID,
      kind: 'reception',
      title: 'V. Grand Celebration of Mami’s 90-Year Legacy',
      startsAt: '2026-11-14T16:00:00+01:00',
      endsAt: '2026-11-14T20:00:00+01:00',
      timeLabel: '04:00 PM – 08:00 PM',
      venueName: 'Marcons and Family Residence, Clerk’s Quarter',
      address: 'Clerk’s Quarter, Limbe, Cameroon',
    },
    {
      id: 'fe-13',
      memorialId: MEMORIAL_ID,
      kind: 'reception',
      title: 'VI. All-Night Animation',
      startsAt: '2026-11-14T20:00:00+01:00',
      timeLabel: '08:00 PM – Till Dawn',
      venueName: 'Family Residence, Clerk’s Quarter',
      address: 'Clerk’s Quarter, Limbe, Cameroon',
    },
    {
      id: 'fe-14',
      memorialId: MEMORIAL_ID,
      kind: 'service',
      title: 'Special Thanksgiving Church Service',
      startsAt: '2026-11-15T10:00:00+01:00',
      endsAt: '2026-11-15T12:30:00+01:00',
      timeLabel: '10:00 AM – 12:30 PM',
      venueName: 'Ebenezer Baptist Church Limbe',
      address: 'Limbe, Cameroon',
    },
    {
      id: 'fe-15',
      memorialId: MEMORIAL_ID,
      kind: 'reception',
      title: 'Thanksgiving Reception',
      startsAt: '2026-11-15T13:30:00+01:00',
      endsAt: '2026-11-15T20:00:00+01:00',
      timeLabel: '01:30 PM – 08:00 PM',
      venueName: 'Family Residence, Clerk’s Quarter',
      address: 'Clerk’s Quarter, Limbe, Cameroon',
    },
    {
      id: 'fe-16',
      memorialId: MEMORIAL_ID,
      kind: 'reception',
      title: 'Sasa / Cultural Feast',
      startsAt: '2026-11-19T16:00:00+01:00',
      timeLabel: '04:00 PM',
      venueName: 'Family Compound Limbola',
      address: 'Limbola, Cameroon',
    },
  ],
  programItems: [],
  galleryAlbums: [
    { id: 'alb-1', memorialId: MEMORIAL_ID, name: 'Portrait', category: 'family', sortOrder: 1 },
    { id: 'alb-2', memorialId: MEMORIAL_ID, name: 'Programme', category: 'funeral', sortOrder: 2 },
  ],
  galleryPhotos: [
    { id: 'gp-1', memorialId: MEMORIAL_ID, albumId: 'alb-1', url: portrait, caption: 'Mami Christiana Enanga Besong', sortOrder: 1 },
    { id: 'gp-2', memorialId: MEMORIAL_ID, albumId: 'alb-2', url: programme, caption: 'Funeral & Thanksgiving Programme, 7–19 November 2026', sortOrder: 1 },
  ],
  tributes: [],
  stories: [],
  mediaItems: [],
  donationCauses: [],
  familyContacts: [
    { id: 'fc-1', memorialId: MEMORIAL_ID, name: 'Chief Moses Obenofunde', relation: 'Cameroon', phone: '+237 682 946 016' },
    { id: 'fc-2', memorialId: MEMORIAL_ID, name: 'Oben Francis Essie', relation: 'Cameroon', phone: '+237 699 961 466' },
    { id: 'fc-3', memorialId: MEMORIAL_ID, name: 'Silo Oben Bertha', relation: 'Cameroon', phone: '+237 677 786 431' },
    { id: 'fc-4', memorialId: MEMORIAL_ID, name: 'Hillary Akem Oben', relation: 'Cameroon', phone: '+237 671 714 730' },
    { id: 'fc-5', memorialId: MEMORIAL_ID, name: 'Benjamin Tanyi Oben', relation: 'Cameroon', phone: '+237 695 955 064' },
    { id: 'fc-6', memorialId: MEMORIAL_ID, name: 'Samuel Njie Besong', relation: 'Germany', phone: '+49 163 176 0291' },
    { id: 'fc-7', memorialId: MEMORIAL_ID, name: 'Obaley Oben Besong', relation: 'Germany', phone: '+49 173 992 3221' },
    { id: 'fc-8', memorialId: MEMORIAL_ID, name: 'Robert Molango Oben', relation: 'Germany', phone: '+49 178 554 8658' },
    { id: 'fc-9', memorialId: MEMORIAL_ID, name: 'Apst Dr. Drusilla Dinka', relation: 'USA', phone: '+1 972 880 2633' },
    { id: 'fc-10', memorialId: MEMORIAL_ID, name: 'Sessekou Awu Moses Besong', relation: 'USA', phone: '+1 617 875 5151' },
    { id: 'fc-11', memorialId: MEMORIAL_ID, name: 'Mrs Helen Enanga Nche', relation: 'USA', phone: '+1 240 645 8767' },
    { id: 'fc-12', memorialId: MEMORIAL_ID, name: 'Edward Besong Oben', relation: 'Canada', phone: '+1 306 717 0771' },
  ],
  aiSettings: {
    id: 'ai-1',
    memorialId: MEMORIAL_ID,
    assistantName: 'Memorial Guide',
    persona:
      'Speak warmly and respectfully, as a gentle guide helping visitors learn about Mami Christiana Enanga Besong and the funeral and thanksgiving programme in Limbe and Limbola.',
    greeting:
      'Hello, I am here to help you learn about Mami Christiana Enanga Besong and the funeral and thanksgiving programme. Feel free to ask me anything.',
    isEnabled: true,
    fallbackMessage: 'I am sorry, I do not have that information. Please contact the family using the details on the Funeral page.',
  },
  aiQuickQuestions: [
    { id: 'qq-1', memorialId: MEMORIAL_ID, label: 'When is the funeral?', questionText: 'When and where is the funeral service?', sortOrder: 1 },
    { id: 'qq-2', memorialId: MEMORIAL_ID, label: 'The programme', questionText: 'What is the funeral and thanksgiving programme?', sortOrder: 2 },
    { id: 'qq-3', memorialId: MEMORIAL_ID, label: 'Who was she?', questionText: 'Who was Mami Christiana Enanga Besong?', sortOrder: 3 },
    { id: 'qq-4', memorialId: MEMORIAL_ID, label: 'Share a memory', questionText: 'How can I share a memory or condolence message?', sortOrder: 4 },
    { id: 'qq-5', memorialId: MEMORIAL_ID, label: 'Family contacts', questionText: 'How can I contact the family?', sortOrder: 5 },
  ],
  aiKnowledgeEntries: [
    {
      id: 'ke-1',
      memorialId: MEMORIAL_ID,
      question: 'What was her maiden name?',
      answer: 'She was born Njie Nambeke. Her full name is Mami Christiana Enanga Besong, née Njie Nambeke.',
      tags: ['name', 'family'],
    },
    {
      id: 'ke-2',
      memorialId: MEMORIAL_ID,
      question: 'When was she born and when did she die?',
      answer: 'Sunrise 24 May 1936. Sunset 14 August 2026. She was 90 years old.',
      tags: ['dates', 'life'],
    },
    {
      id: 'ke-3',
      memorialId: MEMORIAL_ID,
      question: 'What is the funeral programme?',
      answer:
        'The Funeral and Thanksgiving Programme runs from 7 to 19 November 2026. The main funeral service is on Saturday 14 November 2026 from 12:00 PM to 2:00 PM at Ebenezer Baptist Church Limbe. Burial follows at the family compound in Limbola from 3:00 PM to 4:00 PM. Opening of mourning is on 7 November at 4:00 PM at the family residence, Clerk’s Quarter. A special thanksgiving church service is on Sunday 15 November, and a Sasa / cultural feast is on Thursday 19 November at 4:00 PM at the family compound, Limbola.',
      tags: ['funeral', 'programme'],
    },
  ],
};
